### ISSUE TITLE
Research + Implement OAuth

### ISSUE THREAD

**Issue by reznikovl** [brandonnadell/impulse#5]
Subtasks:
- [ ] Research what OAuth framework is best
- [ ] Create a functional login/logout button and have the user be able to sign in

**Comment by akshayheda** [comment]
Found the relevant library: https://github.com/anthonyjgrove/react-google-login

Need to determine when to launch, and how to store login

**Comment by reznikovl** [comment]
Putting on the backburner awaiting a decision on whether a back end is necessary
